---
title: "4 Visualization"
author: "BIOL 5000"
output:
  html_document:
    df_print: paged
  html_notebook:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(gridExtra)
```

```{r Ch4 Code}
#read in datafile
compensation <- read.csv('compensation.csv')
```

```{r}
#plot data
ggplot(compensation, aes(x = Root, y = Fruit)) +
  geom_point()
```

```{r}
#add theme
ggplot(compensation, aes(x = Root, y = Fruit)) +
  geom_point() +
  theme_bw()
```

```{r}
#add multiple customizations
ggplot(compensation, aes(x = Root, y = Fruit, shape = Grazing, color = Grazing)) +
  geom_point(size = 5) +
  xlab("Root Biomass") +
  ylab("Fruit Production") +
  theme_bw()
```

```{r}
#box and whisker plots
ggplot(compensation, aes(x = Grazing, y = Fruit)) +
  geom_boxplot() +
  xlab("Grazing treatment") +
  ylab("Fruit Production") +
  theme_bw()
```

```{r}
ggplot(compensation, aes(x = Grazing, y = Fruit)) +
  geom_boxplot() +
  geom_point(size = 4, color = 'lightgrey', alpha = 0.5) +
  xlab("Grazing treatment") +
  ylab("Fruit Production") +
  theme_bw()
```

#ggplot2 pre-defined colors
browseURL("http://sape.inf.usi.ch/quick-reference/ggplot2/colour")

```{r}
#Plotting distribution of a single variable
ggplot(compensation, aes(x = Fruit)) +
  geom_histogram()
```

```{r}
#Most obvious thing to adjust is bin width:
ggplot(compensation, aes(x = Fruit)) +
  geom_histogram(bins = 10)
```

```{r}
ggplot(compensation, aes(x = Fruit)) +
  geom_histogram(binwidth = 15)
```

```{r}
#faceting
ggplot(compensation, aes(x = Fruit)) +
  geom_histogram(binwidth = 15) +
  facet_wrap(~Grazing)
```

```{r}
#save the plot
ggsave("ThatCoolHistogramOfFruit.png")
```

```{r}
#scales and themes in ggplot2
library(gridExtra)
```

```{r}
# BASE scatterplot
eg_scatter <-
  ggplot(data = compensation, aes(x = Root, y = Fruit)) +
  geom_point()
```

```{r}
# BASE box-and-whiskers plot
eg_box <-
  ggplot(data = compensation, aes(x = Grazing, y = Fruit)) +
  geom_boxplot()
```

```{r}
grid.arrange(eg_scatter, eg_box, nrow = 1)
```

```{r}
#plot customizations
eg_scatter
```

```{r}
#add more intuitive axis labels
eg_scatter + xlab("Root Biomass") + ylab("Fruit Production")
```

```{r}
#re-scale the axes (x,y)
eg_scatter + xlim(0, 20) + ylim(0, 140)
```

```{r}
#putting custom text inside figure ; annotate() function
eg_scatter +
  annotate("text", x = c(6,8), y = c(105, 25),
           label = c("Text up here...","...and text down here"))
```

```{r}
#adjust range of axes, frequency and location of tick marks
eg_scatter + scale_x_continuous(limits = c(4, 11), breaks = 4:11)
```

```{r}
#customizing the colors allocated to each group using scale_colour_manual() layering.
ggplot(data = compensation, aes(x = Root, y = Fruit, colour = Grazing)) +
  geom_point() +
  scale_colour_manual(values = c(Grazed = "brown", 	Ungrazed = "green"))
```

```{r}
#Scale transformation; one or both of the X-Y axes
eg_box +
  scale_y_continuous(breaks = seq(from = 10, to = 150, by = 20), trans = "log10")
```

```{r}
#modify theme elements; powerful framework for adjusting all the non-aesthetic pieces of a graph
eg_scatter +
  theme(
    panel.background = element_rect(fill = NA, color = "black"),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "lightblue")
  )
```

#the theme elements you can adjust
? theme #click on help tab to see possible theme elements

```{r}
#Some theme() syntax for axis titles and ticks
eg_box +
  theme(
    axis.title.x = element_text(colour = "cornflowerblue", size =rel(2)),
    axis.text.x = element_text(angle = 45, size = 13, vjust = 	0.5))
```

```{r}
#We use the scale_x_discrete() or scale_y_discrete() function to 
#customize the labelling of groups
eg_box + scale_x_discrete(limits = c("Ungrazed", "Grazed"), labels = c("Control", "Grazed"))
```

```{r}
#legend position
ggplot(compensation, aes(x = Root, y = Fruit, color = Grazing)) +
  geom_point() +
  theme(legend.position = "none")
```

